version: '3.7'

services:
  postgres:
    image: postgres:14.1
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: comet_quiz_game
      POSTGRES_PASSWORD: "qCDLMVSQSLmqCZj25AZhNzGOtKVH7xhZ"
    volumes:
      - comet_quiz_game_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "oTkBdB0IA1Q-w9OSH8CfRsK-6QHgBbE6"
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  comet_quiz_game_data:
